### ISSUE TITLE
Upgrade provider 'null' to v2.1.2

### ISSUE THREAD

**Issue by sshvetsov** [traveloka/terraform-aws-resource-naming#20]
Since this module has been released, the version of the provider "null" used by this module has been [upgraded multiple times](https://github.com/terraform-providers/terraform-provider-null/blob/master/CHANGELOG.md).

The latest version of the provider "null" is v2.1.2 at the time of this writing.
I think this particular module could be safely upgraded version 2.1.2.

One good reason to upgrade is support for Terraform 0.12.

**Comment by isen-ng** [comment]
I would suggest to relax the provider versions instead of hardcoding it to a specific version.

Terraform recommendations is to not specify providers in child modules but I think there sometimes is a need to specify a minimum version of a provider. Thus I suggest to relax the provider restriction from "1.0.0" to ">= 1.0.0".

This would signal to users that the min version is 1.0.0 but yet I can specify 2.1.2 in my parent terraform if needed.

See: https://github.com/traveloka/terraform-aws-resource-naming/pull/22
